define({
    root: ({
        "account": "Account",
        "account_information": "Account Information",
        "active": "Active",
        "address": "Address",
        "addresses": "Addresses",
        "amount": "Amount",
        "areyousure": "Are you sure?",
        "available": "Available",
        "bill_to": "Bill To",
        "brands": "Brands",
        "cancel": "Cancel",
        "carrier": "Carrier",
        "city": "City",
        "client": "Client",
        "comment": "Comment",
        "confirm": "Confirm",
        "contact": "Contact",
        "contacts": "Contacts",
        "cost": "Cost",
        "country": "Country",
        "date": "Date",
        "dates": "Dates",
        "description": "Description",
        "details": "Details",
        "disabled": "Disabled",
        "email": "Email",
        "enabled": "Enabled",
        "end": "End",
        "entity": "Entity",
        "error": "Error",
        "equipment": "Equipment",
        "expenses": "Expenses",
        "filter": "Filter",
        "firstname": "First name",
        "from": "From",
        "groups": "Groups",
        "history": "History",
        "id": "Id",
        "instructions": "Instructions",
        "invalid": "Invalid",
        "invalid_form": "Invalid data",
        "invite": "Invite",
        "item": "Item",
        "items": "Items",
        "lastname": "Last name",
        "locked": "Locked",
        "manufacturer": "Manufacturer",
        "middlename": "Middle name",
        "name": "Name",
        "new": "New",
        "no": "No",
        "note": "Note",
        "okay": "Okay",
        "order": "Order",
        "person": "Person",
        "phone_number": "Phone number",
        "phone_numbers": "Phone numbers",
        "postal_code": "Zip",
        "purchased": "Purchased",
        "quantity": "Quantity",
        "remove": "Remove",
        "requires": "Requires",
        "roles": "Roles",
        "satisfies": "Satisfies",
        "save": "Save",
        "send": "Send",
        "sent": "Sent",
        "service": "Service",
        "services": "Services",
        "start": "Start",
        "state_province": "State",
        "status": "Status",
        "street": "Street",
        "title": "Title",
        "to": "To",
        "tracking_number": "Tracking Number",
        "type": "Type",
        "url": "URL",
        "user": "User",
        "username": "Username",
        "value": "Value",
        "values": "Values",
        "venue": "Venue",
        "view": "View",
        "yes": "Yes"
    })
});
