define({
    root: ({
        "active": "Active",
        "address": "Address",
        "addresses": "Addresses",
        "areyousure": "Are you sure?",
        "brands": "Brands",
        "cancel": "Cancel",
        "city": "City",
        "comment": "Comment",
        "confirm": "Confirm",
        "contact": "Contact",
        "contacts": "Contacts",
        "country": "Country",
        "disabled": "Disabled",
        "email": "Email",
        "enabled": "Enabled",
        "entity": "Entity",
        "error": "Error",
        "filter": "Filter",
        "firstname": "First name",
        "groups": "Groups",
	"id": "Id",
        "invalid": "Invalid",
        "invalid_form": "Invalid data",
        "invite": "Invite",
        "lastname": "Last name",
        "locked": "Locked",
        "manufacturer": "Manufacturer",
        "mi": "MI",
        "name": "Name",
        "new": "New",
        "no": "No",
        "okay": "Okay",
        "person": "Person",
        "phone_number": "Phone number",
        "phone_numbers": "Phone numbers",
        "postal_code": "Zip",
        "remove": "Remove",
        "roles": "Roles",
        "save": "Save",
        "send": "Send",
        "sent": "Sent",
        "state_province": "State",
        "status": "Status",
        "street": "Street",
        "type": "Type",
        "url": "URL",
        "user": "User",
        "username": "Username",
        "view": "View",
        "yes": "Yes"
    })
});
