api_platform:
    enable_fos_user: true
    mapping:
        paths: []
    resource_class_directories: 
        - '%kernel.project_dir%/src/Entity'
        - '%kernel.project_dir%/src/Entity/Asset'
    formats:
        json:
            mime_types: ['application/json']