imports:
#    - { resource: fos_rest.yaml }
    - { resource: framework.yaml }
    - { resource: framework_extra.yaml }
    - { resource: knp_menu.yaml }
    - { resource: stof_doctrine_extensions.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

#fos_rest:
#    format_listener:
#        enabled: true
#        rules:
#            -
#                # http://symfony.com/doc/current/bundles/FOSRestBundle/format_listener.html
#                path: ^/admin/user
#                priorities: ['json', 'html', 'xml','form']
#               fallback_format: ~
#                methods: [ 'get', 'post', 'put', 'delete']
#            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
#            - { path: '^/', stop: true }
