fos_rest:

    disable_csrf_role: ROLE_API
    view:
        view_response_listener: true
        force_redirects:
            html: true
        formats:
            json: true
        templating_formats:
            json: false
            html: true
        mime_types:
            json: ['application/json', 'application/x-json']
        failed_validation: HTTP_BAD_REQUEST
    body_listener:
        default_format: json
    param_fetcher_listener:
        force: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
        exception: true
    body_converter:
        enabled: true
        validate: false
        # validation_errors_argument: validationErrors # This is the default value
    exception:
        enabled: false
    routing_loader:
        default_format: json
        include_format: false
