framework:
    secret: '%env(APP_SECRET)%'
    #http_method_override: true

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

    #esi:             ~
    translator:      { fallbacks: ["en","%locale%"] }
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enabled: true
        enable_annotations: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme

    trusted_hosts:   ~
    session:
         handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler

    fragments:       ~
    http_method_override: true
