<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * ManufacturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function findChildren()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                "SELECT c FROM AppBundle:Category c WHERE c.name != 'top' ORDER BY c.position ASC"
                        )
                        ->getResult();
    }

}
