<?php

namespace AppBundle\Repository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {
        return $this->findBy( [], ['name' => 'ASC'] );
    }

    public function findByNameLike( $name )
    {
        $name = '%' . str_replace( '*', '%', strtolower( $name ) );

        return $this->getEntityManager()
                        ->createQueryBuilder()->select( ['ct'] )
                        ->from( 'AppBundle\Entity\Client\Contract', 'ct' )
                        ->innerJoin( 'ct.client', 'cl' )
                        ->where( "LOWER(CONCAT(CONCAT(cl.name, ' '), ct.name)) LIKE :client_contract" )
                        ->orderBy( 'cl.name' )
                        ->addOrderBy( 'ct.name' )
                        ->setParameter( 'client_contract', strtolower( $name ) )
                        ->getQuery()
                        ->getResult();
    }

}
