<?php

namespace AppBundle\Repository;

/**
 * EmployeeStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploymentStatusRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                "SELECT es FROM AppBundle\Entity\Staff\EmploymentStatus es ORDER BY es.name ASC"
                        )
                        ->getResult();
    }

}
