<?php

namespace AppBundle\Repository;

/**
 * RoleTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                "SELECT r FROM AppBundle\Entity\Staff\Role r ORDER BY r.name ASC"
                        )
                        ->getResult();
    }

}
