<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Asset\Vendor;

/**
 * VendorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNameLike( $name )
    {
        $name = '%' . str_replace( '*', '%', $name );
        return $this->getEntityManager()
                        ->createQuery(
                                "SELECT v FROM AppBundle\Entity\Asset\Vendor v WHERE v.name LIKE :name ORDER BY v.name ASC"
                        )
                        ->setParameter( 'name', $name )
                        ->getResult();
    }

}
