imports:
    - { resource: config.yml }
    - { resource: parameters_prod.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
            
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"

assetic:
    assets:
        dojo_js:
            inputs:
                - 'vendor/release/dojo/dojo.js'
        main_js:
            inputs:
                - 'vendor/release/app/main.js'
        app_admin_menu_js:
            inputs:
                - 'vendor/release/app/admin/menu.js'
        app_admin_asset_equipment_js:
            inputs:
                - 'vendor/release/app/admin/asset/equipment.js'
        admin_user_js:
            inputs:
                - 'vendor/release/app/admin/user.js'
        test_js:
            inputs:
                - 'vendor/release/app/test.js'
