imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: validation.yml }
    - { resource: doctrine_extensions.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enabled: true
        enable_annotations: true
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    assets:
        version: 'v5'
        version_format: '%%s?version=%%s'
        base_path: ~
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'form/fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        # CSS
        admin_css:
            inputs:
                - 'vendor/font-awesome-4.5.0/font-awesome.min.css'
                - 'app/css/admin/common.css'
                - 'app/css/admin/admin.css'
                - 'app/css/admin/user.css'
                - 'app/css/admin/asset.css'
        # User side - stock Bootstrap
        bootstrap_css:
            inputs:
                - 'vendor/bootstrap-3.3.6-dist/css/bootstrap.css'
                - 'vendor/bootstrap-3.3.6-dist/css/bootstrap-theme.css'
                - 'vendor/font-awesome-4.5.0/font-awesome.min.css'
        # User side - custom Bootstrap (7 column)
        calendar_css:
            inputs:
                - 'vendor/bootstrap-7-col/css/bootstrap.css'
                - 'vendor/bootstrap-7-col/css/bootstrap-theme.css'
                - 'vendor/font-awesome-4.5.0/font-awesome.min.css'
                - 'app/css/user/calendar.css'
        dgrid_css:
            inputs:
                - 'vendor/release/dgrid/css/dgrid.css'
                - 'vendor/release/dgrid/css/skins/tundra.css'
        dojo_dijit_css:
            inputs:
                - 'vendor/release/dojo/resources/dojo.css'
                - 'vendor/release/dojo/resources/dnd.css'
                - 'vendor/release/dijit/themes/tundra/tundra.css'
        # User side - common CSS
        main_css:
            inputs:
                - 'app/css/user/common.css'
        # JavaScript
        # Admin JavaScript
        main_js:
            inputs:
                - 'app/main/main.js'
        bootstrap_js:
            inputs:
                - 'vendor/bootstrap-3.3.6-dist/js/bootstrap.js'
        calendar_js:
            inputs:
                - 'vendor/bootstrap-7-col/js/bootstrap.js'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                
            legacy:
                driver:   '%legacy_database_driver%'
                host:     '%legacy_database_host%'
                port:     '%legacy_database_port%'
                dbname:   '%legacy_database_name%'
                user:     '%legacy_database_user%'
                password: '%legacy_database_password%'
                charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default

        entity_managers:
            default:      
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    AppBundle: ~
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
            legacy:
                connection: legacy
                mappings:                    
                    LegacyBridgeBundle: ~
        
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
           timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
sensio_framework_extra:
    request: { converters: true }
    view: 
        annotations: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    group:
        group_class: AppBundle\Entity\Group
    registration:
        form:
            type: AppBundle\Form\User\RegistrationFormType

fos_rest:
    disable_csrf_role: ROLE_API
    
    view:
        view_response_listener: true
        force_redirects:
            html: true
        formats:
            json: true
        templating_formats:
            json: false
            html: true
        mime_types:
            json: ['application/json', 'application/x-json']
        failed_validation: HTTP_BAD_REQUEST
    body_listener: 
        default_format: json
    param_fetcher_listener: 
        force: true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_converter:
        enabled: true
        validate: true
        # validation_errors_argument: validationErrors # This is the default value
    exception:
        enabled: true
    routing_loader:
        default_format: json
        include_format: false
    format_listener:
        rules:
            -
                # http://symfony.com/doc/current/bundles/FOSRestBundle/format_listener.html
                path: ^/admin/user
                priorities: ['json', 'html', 'xml','form']
                fallback_format: ~
                methods: [ 'get', 'post', 'put', 'delete']
            - { path: '^/', stop: true }
            
knp_menu:
    # use "twig: false" to disable the Twig extension and the TwigRenderer
    twig:
        template: knp_menu.html.twig
    #  if true, enables the helper for PHP templates
    templating: false
    # the renderer to use, list is also available by default
    default_renderer: twig