app_admin_asset_assets:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Asset\AssetsController
    name_prefix:   app_admin_api_assets_
    prefix: /api

app_admin_asset_carriers:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Asset\CarriersController
    name_prefix:   app_admin_api_carrier_
    prefix: /api

app_admin_asset_categories:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Asset\CategoriesController
    name_prefix:   app_admin_api_categories_
    prefix: /api

app_admin_asset_issues:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Asset\IssuesController
    name_prefix:   app_admin_api_issues_
    prefix: /api

app_admin_asset_manufacturers:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Asset\ManufacturersController
    name_prefix:   app_admin_api_manufacturers_
    prefix: /api

app_admin_asset_trailers:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Asset\TrailersController
    name_prefix:   app_admin_api_trailers_
    prefix: /api

app_admin_asset_transfers:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Asset\TransfersController
    name_prefix:   app_admin_api_transfers_
    prefix: /api

app_admin_asset_vendors:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Asset\VendorsController
    name_prefix:   app_admin_api_vendor_
    prefix: /api

app_admin_client_clients:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Client\ClientsController
    name_prefix:   app_admin_api_client_
    prefix: /api

app_admin_common_people:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Common\PeopleController
    name_prefix:   app_admin_api_people_
    prefix: /api

app_admin_common_menu_store:
    resource: app.admin.menu_store_controller
    type:     rest
    class: AppBundle\Controller\Api\Admin\Common\MenuStoreController
    prefix: /api/menustore
    name_prefix: app_admin_api_common_menustore_

app_admin_schedule_events:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Schedule\EventsController
    name_prefix:   app_admin_api_schedule_
    prefix: /api

app_admin_user_groups:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\User\GroupsController
    name_prefix:   app_admin_api_user_groups_
    prefix: /api

app_admin_users:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\User\UsersController
    name_prefix:   app_admin_api_user_
    prefix: /api

app_admin_users_invitations:
    type: rest
    resource: AppBundle\Controller\Api\Admin\User\InvitationsController
    name_prefix: app_admin_api_user_invitation_
    prefix: /api

app_admin_venue_venues:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Venue\VenuesController
    name_prefix:   app_admin_api_venue_
    prefix: /api
