app_admin:
    resource: Common\AppBundle\Controller\Web\Admin\AdminController
    name_prefix: common_app_web_admin_
    type: rest

app_admin_users:
    type:     rest
    resource: Common\AppBundle\Controller\Api\UsersController
    name_prefix:   common_app_admin_user_
    prefix: /api
    
app_admin_users_invitations:
    type: rest
    resource: Common\AppBundle\Controller\Api\InvitationsController
    name_prefix: common_app_admin_user_invitation
    prefix: /api