app_admin_users:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\User\UsersController
    name_prefix:   app_admin_api_user_
    prefix: /api
    
app_admin_users_invitations:
    type: rest
    resource: AppBundle\Controller\Api\Admin\User\InvitationsController
    name_prefix: app_admin_api_user_invitation_
    prefix: /api

app_admin_asset_manufacturers:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Asset\ManufacturersController
    name_prefix:   app_admin_api_manufacturers_
    prefix: /api

app_admin_asset_vendors:
    type:     rest
    resource: AppBundle\Controller\Api\Admin\Asset\VendorsController
    name_prefix:   app_admin_api_vendor_
    prefix: /api