app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
app_admin_rest:
    type: rest
    resource: routing_admin_rest.yml

static:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/privacy.html.twig
        maxAge:       86400
        sharedAge:    86400
        
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
