app:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation

app_user:
    resource: "@AppBundle/Controller/User"
    type:     annotation
    
admin_rest:
    type: rest
    resource: routing_rest.yml
    
legacy_app:
    resource: "@LegacyBridgeBundle/Resources/config/routing.yml"
    prefix:   / 
    
static:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/privacy.html.twig
        maxAge:       86400
        sharedAge:    86400
        
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
