app_admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation
  
app_api_store:
    resource: "@AppBundle/Controller/Api/Common"
    type:   annotation

app_common:
    resource: "@AppBundle/Controller/Common"
    type:     annotation

app_public:
    resource: "@AppBundle/Controller"
    type:     annotation

#app_publick:
#    resource: "@AppBundle/Controller/Publick"
#    type:     annotation

app_user:
    resource: "@AppBundle/Controller/User"
    type:     annotation

app_api:
    type: rest
    resource: routing_rest.yml

admin_rest:
    type: rest
    resource: routing_rest.yml

# Using this routing configuration allows dependency injection from services.yml
# It may not be perfect, but it is working
app_admin_api_common_menustore_getadminmenus:
    defaults: { _controller: app.admin.menu_store_controller:getAdminmenuAction }
    path: /api/menustore/adminmenus
    methods: GET

app_admin_api_common_menustore_getadminmenus_alt:
    defaults: { _controller: app.admin.menu_store_controller:getAdminmenuAction }
    path: /api/menustore/adminmenus/
    methods: GET

app_admin_api_common_menustore_getadminmenus_parent:
    defaults: { _controller: app.admin.menu_store_controller:getAdminmenuAction }
    path: /api/menustore/adminmenus/?parent={parent}
    methods: GET

app_admin_api_common_menustore_getadminmenus_id:
    defaults: { _controller: app.admin.menu_store_controller:getAdminmenuAction }
    path: /api/menustore/adminmenus/{id}
    methods: GET

legacy_app:
    resource: "@LegacyBridgeBundle/Resources/config/routing.yml"
    prefix:   / 
    
static:
    path: /privacy
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/privacy.html.twig
        maxAge:       86400
        sharedAge:    86400
        
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
