imports:
    - { resource: "@LegacyBridgeBundle/Resources/config/security.yml" }

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    # Be sure to update the role validation for the User entity!
    role_hierarchy:
        ROLE_API:
        ROLE_USER:
        ROLE_ADMIN:       ROLE_USER
        ROLE_ADMIN_USER:  ROLE_ADMIN
        ROLE_ADMIN_USER_ADMIN: [ROLE_API,ROLE_ADMIN,ROLE_ADMIN_USER]      
        ROLE_SUPER_ADMIN: ROLE_ADMIN, ROLE_ADMIN_USER_ADMIN
    providers:
        chain_provider:
            chain:
                providers: [ fos_userbundle, legacy_user_provider ]
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: chain_provider
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                #always_remember_me: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/group/, role: ROLE_ADMIN }
