imports:
    - { resource: "@LegacyBridgeBundle/Resources/config/services.yml" }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    # JSON Encoder
    app.encoder.json:
        class: 'Symfony\Component\Serializer\Encoder\JsonEncoder'

    app.normalizer.object:
        class: 'AppBundle\Serializer\Normalizer\Normalizer'
        public: false
        tags:
            - { name: serializer.normalizer }

    app.serializer.default:
        class: 'Symfony\Component\Serializer\Serializer'
        arguments:
            0:
                - '@app.normalizer.object'
            1:
                - '@app.encoder.json'

    app.admin.form.type.asset:
        class: AppBundle\Form\Admin\Asset\AssetType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_asset_type' }

    app.admin.form.type.barcode:
        class: AppBundle\Form\Admin\Asset\BarcodeType
        tags:
            - { name: form.type, alias: 'app_barcode_type' }

    app.admin.form.type.model:
        class: AppBundle\Form\Admin\Asset\ModelType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_model_type' }

    app.admin.form.type.test:
        class: AppBundle\Form\TestType
        arguments: ['@security.authorization_checker','%security.role_hierarchy.roles%']
        tags:
        - { name: form.type, alias: user }

    app.admin.form.type.user:
        class: AppBundle\Form\Admin\User\UserType
        arguments: ['@security.authorization_checker','%security.role_hierarchy.roles%']
        tags:
        - { name: form.type, alias: user }

    app.admin.menu_voter_request:
        class: AppBundle\Menu\RequestVoter
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.voter }

    app.form.data_transformer.barcode:
        class: AppBundle\Form\Admin\Asset\DataTransformer\BarcodeToEntityTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false    

    app.form.data_transformer.invitation:
        class: AppBundle\Form\User\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false
        
    app.form.data_transformer.model:
        class: AppBundle\Form\Admin\Asset\DataTransformer\ModelToIdTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false    
        
    app.form.invitation:
        class: AppBundle\Form\User\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
            - { name: "form.type", alias: "app_invitation_type" }

    app.form.person:
        class: AppBundle\Form\Common\PersonFormType
        tags:
            - { name: "form.type", alias: "app_common_person" }
    
    app.form.registration:
        class: AppBundle\Form\User\RegistrationFormType
        tags:
            - { name: "form.type", alias: "app_user_registration" }
        
    app.form.user:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - user_form                        # name of the form
            - user                             # alias of the form type
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Registration] } # validation groups
               
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }
            - { name: knp_menu.menu_builder, method: createCalendarMenu, alias: calendar }
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createUserMenu, alias: user }

    app.menu_renderer:
        # The class implements Knp\Menu\Renderer\RendererInterface
        class: AppBundle\Menu\JsonRenderer
        arguments: [ "@twig",  "knp_menu.html.twig", "@knp_menu.matcher", {"translator": "@translator" }]
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.renderer, alias: json }
            
    app.menu_voter_request:
        class: AppBundle\Menu\RequestVoter
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.voter }
            
    app.model.person:
        class: AppBundle\Model\Person
        arguments: ["@doctrine.orm.entity_manager","@app.util.phone_number","@app.util.email","@app.util.address"]
        
    app.util.dstore:
        class: AppBundle\Util\DStore
                   
    app.util.address:
        class: AppBundle\Util\Address
        arguments: ['@doctrine.orm.entity_manager']

    app.util.brand:
        class: AppBundle\Util\Brand
        arguments: ['@doctrine.orm.entity_manager']
        
    app.util.contact:
        class: AppBundle\Util\Contact
        arguments: ['@doctrine.orm.entity_manager', '@app.model.person']
        
    app.util.email:
        class: AppBundle\Util\Email 
        arguments: ['@doctrine.orm.entity_manager']

    app.util.form:
        class: AppBundle\Util\Form
        
    app.util.log:
        class: AppBundle\Util\Log
        arguments: ['@doctrine.orm.entity_manager']
        
    app.util.model:
        class: AppBundle\Util\Model
        arguments: ['@doctrine.orm.entity_manager']
        
    app.util.phone_number:
        class: AppBundle\Util\PhoneNumber
        arguments: ['@doctrine.orm.entity_manager']
        
    app.util.user:
        class: AppBundle\Util\User
        arguments: ["@fos_user.group_manager"]

    fos_user.doctrine_registry:
        alias: doctrine