imports:
    - { resource: "@LegacyBridgeBundle/Resources/config/services.yml" }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.admin.form.type.user:
        class: AppBundle\Form\Admin\User\UserType
        arguments: ['@security.authorization_checker','%security.role_hierarchy.roles%']
        tags:
        - { name: form.type, alias: user }

    app.admin.menu_voter_request:
        class: AppBundle\Menu\RequestVoter
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.voter }

    app.form.data_transformer.invitation:
        class: AppBundle\Form\User\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false
        
    app.form.invitation:
        class: AppBundle\Form\User\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
            - { name: "form.type", alias: "app_invitation_type" }

    app.form.person:
        class: AppBundle\Form\Common\PersonFormType
        tags:
            - { name: "form.type", alias: "app_common_person" }
    
    app.form.registration:
        class: AppBundle\Form\User\RegistrationFormType
        tags:
            - { name: "form.type", alias: "app_user_registration" }
        
    app.form.user:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - user_form                        # name of the form
            - user                             # alias of the form type
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Registration] } # validation groups
               
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }
            - { name: knp_menu.menu_builder, method: createCalendarMenu, alias: calendar }
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createUserMenu, alias: user }

    app.menu_voter_request:
        class: AppBundle\Menu\RequestVoter
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.voter }

    app.model.person:
        class: AppBundle\Model\Person
        arguments: ["@doctrine.orm.entity_manager","@app.util.phone_number","@app.util.email","@app.util.address"]
        
    app.util.dstore:
        class: AppBundle\Util\DStore
                   
    app.util.address:
        class: AppBundle\Util\Address
        arguments: ['@doctrine.orm.entity_manager']

    app.util.brand:
        class: AppBundle\Util\Brand
        arguments: ['@doctrine.orm.entity_manager', '@app.util.model']
        
    app.util.contact:
        class: AppBundle\Util\Contact
        arguments: ['@doctrine.orm.entity_manager', '@app.model.person']
        
    app.util.email:
        class: AppBundle\Util\Email 
        arguments: ['@doctrine.orm.entity_manager']

    app.util.form:
        class: AppBundle\Util\Form
        
    app.util.model:
        class: AppBundle\Util\model
        arguments: ['@doctrine.orm.entity_manager']
        
    app.util.phone_number:
        class: AppBundle\Util\PhoneNumber
        arguments: ['@doctrine.orm.entity_manager']
        
    app.util.user:
        class: AppBundle\Util\User
        arguments: ["@fos_user.group_manager"]

    fos_user.doctrine_registry:
        alias: doctrine