

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:

    app.form.registration:
        class: AppBundle\Form\User\RegistrationFormType
        tags:
            - { name: "form.type", alias: "app_user_registration" }

    app.form.invitation:
        class: AppBundle\Form\User\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
            - { name: "form.type", alias: "app_invitation_type" }

    app.form.data_transformer.invitation:
        class: AppBundle\Form\User\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false
        
    app.util.dstore:
        class: AppBundle\Util\DStore
        
    app.util.form:
        class: AppBundle\Util\Form
        
    app.form.user:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - user_form                        # name of the form
            - user                             # alias of the form type
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Registration] } # validation groups

    app.form.type.user:
        class: AppBundle\Form\Admin\User\UserType
        arguments: ['%security.role_hierarchy.roles%']
        tags:
        - { name: form.type, alias: user }
             
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

    fos_user.doctrine_registry:
        alias: doctrine