imports:
    - { resource: "@LegacyBridgeBundle/Resources/config/services.yml" }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    entity_menus:
        [ clients, manufacturers, trailers, vendors, venues ]

    location_type.entities:
        asset: 'AppBundle\Entity\Asset\Asset'
        client: 'AppBundle\Entity\Client\Client'
        contact: 'AppBundle\Entity\Common\Contact'
        manufacturer: 'AppBundle\Entity\Common\Contact'
        other:
        shop:
        trailer: 'AppBundle\Entity\Asset\Trailer'
        vendor: 'AppBundle\Entity\Asset\Vendor'
        venue: 'AppBundle\Entity\Common\Contact'

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:

    # JSON Encoder
    app.encoder.json:
        class: 'Symfony\Component\Serializer\Encoder\JsonEncoder'

    app.normalizer.object:
        class: 'AppBundle\Serializer\Normalizer\Normalizer'
        public: false
        tags:
            - { name: serializer.normalizer }

    app.serializer.default:
        class: 'Symfony\Component\Serializer\Serializer'
        arguments:
            0:
                - '@app.normalizer.object'
            1:
                - '@app.encoder.json'

    app.form.data_transformer.category:
        class: AppBundle\Form\Admin\Asset\DataTransformer\CategoryToIdTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false

    app.form.data_transformer.contact:
        class: AppBundle\Form\Admin\Common\DataTransformer\ContactToIdTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false

    app.form.data_transformer.contract:
        class: AppBundle\Form\Admin\Client\DataTransformer\ContractToIdTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false

    app.form.data_transformer.event_trailer:
        class: AppBundle\Form\Admin\Client\DataTransformer\TrailerToIdTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false

    app.form.data_transformer.invitation:
        class: AppBundle\Form\User\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false

    app.form.data_transformer.model:
        class: AppBundle\Form\Admin\Asset\DataTransformer\ModelToIdTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false

    app.form.data_transformer.person_type:
        class: AppBundle\Form\Common\DataTransformer\PersonToIdTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false

    app.admin.form.type.asset:
        class: AppBundle\Form\Admin\Asset\AssetType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_asset_type' }

    app.admin.form.type.barcode:
        class: AppBundle\Form\Admin\Asset\BarcodeType
        tags:
            - { name: form.type, alias: 'app_barcode_type' }

    app.admin.form.type.asset_location_type_type:
        class: AppBundle\Form\Admin\Asset\AssetLocationType
        arguments: ['@doctrine.orm.entity_manager','%location_type.entities%']
        tags:
            - { name: form.type, alias: 'app_asset_location_type' }

    app.admin.field.type.category:
        class: AppBundle\Form\Admin\Asset\Type\CategoryType
        arguments: ['@app.form.data_transformer.category']
        tags:
            - { name: form.type, alias: 'app_category_type' }

    app.admin.form.type.category_quantity:
        class: AppBundle\Form\Admin\Client\CategoryQuantityType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_category_quantity_type' }

    app.admin.form.type.contact:
        class: AppBundle\Form\Admin\Common\ContactType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_contact_type' }

    app.admin.field.type.contract:
        class: AppBundle\Form\Admin\Client\Type\ContractType
        arguments: ['@app.form.data_transformer.contract']
        tags:
            - { name: form.type, alias: 'app_client_contract_type' }

    app.admin.form.type.event:
        class: AppBundle\Form\Admin\Schedule\EventType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_schedule_event_type' }

    app.admin.field.type.event_trailer:
        class: AppBundle\Form\Admin\Schedule\Type\TrailerType
        arguments: ['@app.form.data_transformer.event_trailer']
        tags:
            - { name: form.type, alias: 'app_event_trailer_type' }

    app.admin.form.type.group:
        class: AppBundle\Form\Admin\User\GroupType
        arguments: ['@security.authorization_checker','%security.role_hierarchy.roles%']
        tags:
        - { name: form.type, alias: group }

    app.admin.form.type.issue:
        class: AppBundle\Form\Admin\Asset\IssueType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_admin_asset_issue_type' }

    app.admin.form.type.issue_item:
        class: AppBundle\Form\Admin\Asset\IssueItemType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_admin_asset_issue_item_type' }

    app.admin.form.type.location_type:
        class: AppBundle\Form\Admin\Asset\LocationTypeType
        arguments: ['%location_type.entities%']
        tags:
            - { name: form.type, alias: 'app_admin_asset_location_type_type' }

    app.admin.form.type.model:
        class: AppBundle\Form\Admin\Asset\ModelType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_model_type' }

    app.admin.field.type.model_relationship:
        class: AppBundle\Form\Admin\Asset\Type\ModelRelationshipType
        arguments: ['@app.form.data_transformer.model']
        tags:
            - { name: form.type, alias: 'app_model_relationship_type' }

    app.admin.form.type.person:
        class: AppBundle\Form\Common\PersonType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_person_type' }

    app.admin.form.type.time_span:
        class: AppBundle\Form\Admin\Schedule\TimeSpanType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_time_span_type' }

    app.admin.form.type.trailer.asset:
        class: AppBundle\Form\Admin\Asset\TrailerType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_trailer_asset_type' }

    app.admin.form.type.trailer.client:
        class: AppBundle\Form\Admin\Client\TrailerType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_trailer_client_type' }

    app.admin.form.type.transfer_bill_to:
        class: AppBundle\Form\Admin\Common\BillToType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_admin_transfer_bill_to_type' }

    app.admin.form.type.transfer_item:
        class: AppBundle\Form\Admin\Asset\TransferItemType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_admin_asset_transfer_item_type' }

    app.admin.form.type.transfer:
        class: AppBundle\Form\Admin\Asset\TransferType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_transfer_type' }

    app.admin.form.type.user:
        class: AppBundle\Form\Admin\User\UserType
        arguments: ['@security.authorization_checker','%security.role_hierarchy.roles%']
        tags:
        - { name: form.type, alias: user }

    app.admin.form.type.vendor:
        class: AppBundle\Form\Admin\Asset\VendorType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: 'app_vendor_type' }

    app.admin.menu_voter_request:
        class: AppBundle\Menu\RequestVoter
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.voter }

    app.admin.menu_store_controller:
        class: AppBundle\Controller\Api\Admin\Common\MenuStoreController
        arguments: ['%entity_menus%']
        calls:
            - [setContainer, ["@service_container"]]

    app.form.invitation:
        class: AppBundle\Form\User\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
            - { name: "form.type", alias: "app_invitation_type" }

    app.form.person:
        class: AppBundle\Form\Common\Type\PersonType
        arguments: ['@app.form.data_transformer.person_type']
        tags:
            - { name: "form.type", alias: "app_common_person" }

    app.form.registration:
        class: AppBundle\Form\User\RegistrationFormType
        tags:
            - { name: "form.type", alias: "app_user_registration" }

    Symfony\Component\Form\Form: ~

    app.form.user:
        factory: 'Symfony\Component\Form\Form:createNamed'
        class: 'Symfony\Component\Form\Form'
        arguments:
            - user_form                        # name of the form
            - user                             # alias of the form type
            - null                             # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [Registration] } # validation groups

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }
            - { name: knp_menu.menu_builder, method: createCalendarMenu, alias: calendar }
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createTrailerMenu, alias: trailer }
            - { name: knp_menu.menu_builder, method: createUserMenu, alias: user }


    app.menu_renderer:
        # The class implements Knp\Menu\Renderer\RendererInterface
        class: AppBundle\Menu\JsonRenderer
        arguments: [ "@twig",  "knp_menu.html.twig", "@knp_menu.matcher", {"translator": "@translator" }]
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.renderer, alias: json }

    app.menu_voter_request:
        class: AppBundle\Menu\RequestVoter
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.voter }

    app.util.dstore:
        class: AppBundle\Util\DStore

    app.util.form:
        class: AppBundle\Util\Form
        arguments: ['@session.handler.memcached']

    app.util.log:
        class: AppBundle\Util\Log
        arguments: ['@doctrine.orm.entity_manager']

    app.util.user:
        class: AppBundle\Util\User
        arguments: ["@fos_user.group_manager"]

    fos_user.doctrine_registry:
        alias: doctrine

    session.memcached:
        class: Memcached
        calls:
            - [ addServer, [ '%session_memcached_host%', '%session_memcached_port%' ]]

    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: ['@session.memcached', { prefix: '%session_memcached_prefix%', expiretime: '%session_memcached_expire%' }]
