security:
    encoders:
       Legacy\LegacyAuthBundle\Entity\LegacyUser: bcrypt
       
    providers:
        legacy_user_provider:
            entity: 
                class: LegacyAuthBundle:LegacyUser
                property: username
                manager_name: legacy