security:
    encoders:
        LegacyBridgeBundle\Entity\LegacyUser: 
            algorithm: md5
            encode_as_base64: false
            iterations: 0
       
    providers:
        legacy_user_provider:
            entity: 
                class: LegacyBridgeBundle:LegacyUser
                property: username
                manager_name: legacy