security:
    encoders:
        LegacyBridgeBundle\Entity\LegacyUser: 
            id: legacy_plain_md5_password_encoder
            hash_algorithm: md5
            encode_as_base64: false
       
    providers:
        legacy_user_provider:
            entity: 
                class: LegacyBridgeBundle:LegacyUser
                property: username
                manager_name: legacy