<?php

Namespace App\Repository;

/**
 * ContactTypeApp\Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactTypeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {
        return $this->findBy( [], ['entity' => 'ASC'] );
    }

    public function findOneByAddress( $addressId )
    {
        return $this->getEntityManager()
                        ->createQueryBuilder()->select( ['p'] )
                        ->from( 'App\Entity\Common\Contact', 'c' )
                        ->innerJoin( 'c.address_id', 'a' )
                        ->where( 'a.id = :address_id' )
                        ->limit( 1 )
                        ->setParameter( 'address_id', $addressId )
                        ->getQuery()
                        ->getResult();
    }
}