<?php

Namespace App\Repository;

use App\Entity\Asset\IssueStatus;

/**
 * ManufacturerApp\Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueStatusRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAll()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                "SELECT i FROM App\Entity\Asset\IssueStatus i ORDER BY i.order ASC"
                        )
                        ->getResult();
    }

}
