# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
           
           
    admin.form.type.user:
        class: Common\AdminBundle\Form\User\UserType
        arguments: ['%security.role_hierarchy.roles%']
        tags:
        - { name: form.type, alias: user }
        
    admin.menu_builder:
        class: Common\AdminBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }

    admin.menu_voter_request:
        class: Common\AdminBundle\Menu\RequestVoter
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.voter }
            
    admin.util.dstore:
        class: Common\AdminBundle\Util\DStore
        
    admin.util.form:
        class: Common\AdminBundle\Util\Form
        
    admin.util.group:
        class: Common\AdminBundle\Util\Group
        arguments: ["@fos_user.group_manager"]
  
    admin.util.person:
        class: Common\AdminBundle\Util\Person
        
    admin.util.role:
        class: Common\AdminBundle\Util\Role